import { ThemeProvider } from '@0xsequence/design-system'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
import '@0xsequence/design-system/styles.css'

import { wagmiConfig, kitConfig } from '../config'

import { Providers } from './Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme="dark">
          <Providers wagmiConfig={wagmiConfig} kitConfig={kitConfig}>
            {children}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  )
}
