import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@0xsequence/design-system/styles.css'

import { Web3Provider } from './Web3Provider'
import { ThemeProvider } from '@0xsequence/design-system'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme="dark">
          <Web3Provider>{children}</Web3Provider>
        </ThemeProvider>
      </body>
    </html>
  )
}
